#!/usr/bin/env python3
"""Writes DASHBOARD.md from socialus-web Issues and PRs (gh). Same layout every run.
Usage: python3 scripts/dashboard.py [out]   (default DASHBOARD.md at the repo root)"""
import json, re, subprocess, sys
from datetime import datetime, date
from zoneinfo import ZoneInfo

REPO = 'donlafranchi/socialus-web'
MILESTONE = 'Beta 10-30'
FREEZE = date(2026, 10, 23)
LIVE = 'https://socialus.org'
AREAS = ['page-editing', 'sign-in-you', 'explore-map', 'create-posts',
         'sharing-links', 'builders-seed', 'moderation', 'ops']
STAGES = ['Built', 'Tested', 'Agent-reviewed', 'PM reviewed', 'Bugs clear', 'Done']
GREEN = {'SUCCESS', 'SKIPPED', 'NEUTRAL'}
RED = {'FAILURE', 'TIMED_OUT', 'CANCELLED', 'ERROR', 'ACTION_REQUIRED', 'STARTUP_FAILURE'}


def gh(*args):
    out = subprocess.run(['gh', *args], check=True, capture_output=True, text=True).stdout
    return json.loads(out)


def labels(x):
    return {l['name'] for l in x.get('labels', [])}


def link(n):
    return f'[#{n}](https://github.com/{REPO}/issues/{n})'


def first_live_url(*texts):
    for t in texts:
        m = re.search(r'https://[^\s)>\]]*socialus\.org[^\s)>\]]*', t or '')
        if m:
            return m.group(0).rstrip('.,')
    return None


issues = gh('issue', 'list', '-R', REPO, '--state', 'all', '--milestone', MILESTONE,
            '--limit', '500', '--json', 'number,title,state,labels,body,url')
open_bugs = gh('issue', 'list', '-R', REPO, '--state', 'open', '--label', 'bug',
               '--limit', '500', '--json', 'number,title,body')
prs = gh('pr', 'list', '-R', REPO, '--state', 'all', '--limit', '400',
         '--json', 'number,title,body,state,mergedAt,labels,statusCheckRollup,'
                   'closingIssuesReferences,headRefName')

by_issue = {}
for p in prs:
    refs = {r['number'] for r in p.get('closingIssuesReferences') or []}
    m = re.match(r'^(?:bug|change|chore|fix)[^#:]*#(\d+)', p['title'], re.I)
    if m:
        refs.add(int(m.group(1)))
    m = re.match(r'^(?:bug-|change-|chore-)?(\d+)-', p['headRefName'] or '')
    if m:
        refs.add(int(m.group(1)))
    for n in refs:
        by_issue.setdefault(n, []).append(p)


def best_pr(n):
    cands = by_issue.get(n, [])
    merged = sorted((p for p in cands if p['mergedAt']), key=lambda p: p['mergedAt'])
    if merged:
        return merged[-1]
    opened = [p for p in cands if p['state'] == 'OPEN']
    return max(opened, key=lambda p: p['number']) if opened else None


def ci(pr):
    roll = pr.get('statusCheckRollup') or []
    if not roll:
        return '?'
    states = [(c.get('conclusion') or c.get('state') or c.get('status') or '').upper() for c in roll]
    if any(s in RED for s in states):
        return '○'
    return '●' if all(s in GREEN for s in states) else '○'


def stages(i):
    n = i['number']
    pr = best_pr(n)
    is_bug = 'bug' in labels(i)
    built = '●' if pr and pr['mergedAt'] else '○'
    if is_bug and i['state'] == 'CLOSED':
        built = '●'
    tested = (ci(pr) if built == '●' and pr else '○')
    if built == '●' and not pr:
        tested = '?'
    if pr:
        reviewed = '●' if 'Reviewed by:' in (pr.get('body') or '') and 'review-skipped' not in labels(pr) else '○'
    else:
        reviewed = '○'
    pm = '●' if 'pm-reviewed' in labels(i) or (pr and 'pm-reviewed' in labels(pr)) else '○'
    if is_bug:
        bugs = '●' if i['state'] == 'CLOSED' else '○'
    else:
        pat = re.compile(rf'#{n}\b')
        bugs = '○' if any(pat.search((b['title'] or '') + ' ' + (b['body'] or '')) for b in open_bugs) else '●'
    if built != '●':
        bugs = '○'
    s = [built, tested, reviewed, pm, bugs]
    done = '●' if all(x == '●' for x in s) else ('○' if '○' in s else '?')
    return s + [done], pr


rows = []
for i in issues:
    area = next((l[5:] for l in labels(i) if l.startswith('area:')), None)
    st, pr = stages(i)
    rows.append({'n': i['number'], 'title': re.sub(r'^(change|bug|chore) · ', '', i['title']),
                 'area': area, 'st': st, 'pr': pr, 'open': i['state'] == 'OPEN',
                 'blocking': 'launch-blocking' in labels(i),
                 'review': first_live_url(i.get('body'), (pr or {}).get('body'))})

now = datetime.now(ZoneInfo('America/Los_Angeles'))
days = (FREEZE - now.date()).days
total = len(rows)
done = sum(1 for r in rows if r['st'][5] == '●')

out = [f'# {MILESTONE} · {days} days to freeze · {done} of {total} beta items done · updated {now.strftime("%Y-%m-%d %H:%M")} PT', '',
       '*Generated by `scripts/dashboard.py`; never hand-edited. `?` means the data to tell was not found.*', '',
       '| Area | Progress | Done | Note |', '|---|---|---|---|']

behind = []
for a in AREAS:
    rs = [r for r in rows if r['area'] == a]
    if not rs:
        out.append(f'| {a} | ▱▱▱▱▱▱ | 0 of 0 | no beta items |')
        continue
    filled = 0
    for k in range(6):
        if all(r['st'][k] == '●' for r in rs):
            filled += 1
        else:
            break
    unknown = sum(1 for r in rs if '?' in r['st'])
    nxt = STAGES[filled] if filled < 6 else None
    built = sum(1 for r in rs if r['st'][0] == '●')
    note = f'{built} of {len(rs)} built'
    if nxt:
        waiting = sum(1 for r in rs if r['st'][filled] != '●')
        note += f'; {waiting} waiting on {nxt}'
    if unknown:
        note += f'; {unknown} with a ?'
    out.append(f'| {a} | {"▰" * filled}{"▱" * (6 - filled)} | {sum(1 for r in rs if r["st"][5] == "●")} of {len(rs)} | {note} |')
    if any(r['blocking'] and r['open'] and r['st'][0] != '●' for r in rs):
        behind.append(a)

unassigned = [r for r in rows if r['area'] is None]
if unassigned:
    out += ['', f'*{len(unassigned)} beta item(s) have no `area:` label: ' + ', '.join(link(r['n']) for r in unassigned) + '.*']

for a in AREAS:
    rs = sorted((r for r in rows if r['area'] == a), key=lambda r: r['n'])
    out += ['', f'<details><summary><b>{a}</b> · {len(rs)} item(s)</summary>', '',
            '| Stages | Feature | Review | Link |', '|---|---|---|---|']
    for r in rs:
        pr = f' · [PR #{r["pr"]["number"]}](https://github.com/{REPO}/pull/{r["pr"]["number"]})' if r['pr'] else ''
        rv = f'[Review]({r["review"]})' if r['review'] else '?'
        out.append(f'| `{"".join(r["st"])}` | {r["title"]} | {rv} | {link(r["n"])}{pr} |')
    if not rs:
        out.append('| | none yet | | |')
    out += ['', '</details>']

out += ['', 'Stages, in order: ' + ' → '.join(STAGES) + '. `●` yes · `○` no · `?` not found.', '']
if not behind:
    ratio = lambda a: (sum(1 for r in rows if r['area'] == a and r['st'][0] == '●') /
                       max(1, sum(1 for r in rows if r['area'] == a)))
    present = [a for a in AREAS if any(r['area'] == a for r in rows)]
    overall = sum(1 for r in rows if r['st'][0] == '●') / max(1, total)
    behind = [a for a in present if ratio(a) < overall]
out.append('**Behind:** ' + (', '.join(behind) if behind else 'none') +
           ' *(an open launch-blocking item not yet built; else below the overall built share)*')

nxt = next((r for r in sorted(rows, key=lambda r: (not r['blocking'], r['n']))
            if r['open'] and r['st'][:3] == ['●', '●', '●'] and r['st'][3] != '●'), None)
if nxt:
    cta = f'Review {nxt["title"]} ({link(nxt["n"])})' + (f' at [the live page]({nxt["review"]})' if nxt['review'] else '') + ', then label it `pm-reviewed`.'
else:
    cta = 'none: nothing is waiting on you.'
out.append('')
out.append(f'**Your next action:** {cta}')

path = sys.argv[1] if len(sys.argv) > 1 else 'DASHBOARD.md'
open(path, 'w').write('\n'.join(out) + '\n')
print(f'wrote {path}: {done} of {total} done')
