#!/usr/bin/env bash
# Emits the facts WHERE-IT-IS.md's working lists are built from.
# Judgement sections are NOT produced here — see process/LIVING-DOCS.md.
#
# Usage: bash scripts/state.sh [path-to-socialus-web]   (default ../socialus-web)
set -euo pipefail

PLAN_REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CODE_REPO="${1:-$(cd "$PLAN_REPO/../socialus-web" && pwd)}"
g() { git -C "$CODE_REPO" --no-optional-locks "$@"; }
fail=0
note() { printf '%s\n' "$*"; }

# ---------------------------------------------------------------- guard rails
# Four checks encoded from mistakes made building WHERE-IT-IS.md by hand.
# See socialus-web #96.

# 1. Never read an unfetched checkout.
for r in "$PLAN_REPO" "$CODE_REPO"; do
  git -C "$r" fetch --all --prune --quiet || { echo "FATAL: fetch failed in $r" >&2; exit 1; }
done

# 2. Never use --no-merged here: this repo squash-merges, so a merged branch's
#    tip is never an ancestor of main and is listed unmerged forever.
BANNED="no""-merged"
if grep -rhs -- "--$BANNED" "$PLAN_REPO/scripts" 2>/dev/null | grep -v '^[[:space:]]*#' | grep -qv 'BANNED='; then
  echo "FATAL: --$BANNED used in a script; meaningless in a squash-merging repo" >&2; exit 1
fi

# 3. gh must be authenticated, or issue state is guesswork.
gh auth status >/dev/null 2>&1 || { echo "FATAL: gh not authenticated" >&2; exit 1; }

# 4. Prefer an existing measurement to a grep.
INVENTORY_PATH="docs/copy-inventory.md"   # read from origin/main, never the working tree

REPO="$(g remote get-url origin)"; REPO="${REPO%.git}"; REPO="${REPO#*github.com/}"; REPO="${REPO#*github.com:}"
MAIN="$(g rev-parse --short origin/main)"
MAIN_DATE="$(g log -1 --format=%ad --date=short origin/main)"
LOCAL="$(g rev-parse --short HEAD 2>/dev/null || echo none)"

cat <<HDR
<!-- generated by scripts/state.sh on $(date -u +%Y-%m-%dT%H:%MZ) -->
<!-- origin/main $MAIN ($MAIN_DATE) · local HEAD $LOCAL · fetched -->
HDR
[ "$LOCAL" != "$MAIN" ] && note "" && note "> **Local checkout is not on origin/main** ($LOCAL vs $MAIN). Facts below come from origin/main."

# ------------------------------------------------------------------- to build
note ""; note "## To build — open issues"
gh issue list --repo "$REPO" --state open --limit 200 \
  --json number,title,labels \
  -q '.[] | "- #\(.number) \(.title)" + (if (.labels|map(.name)|index("launch-blocking")) then "  **LAUNCH-BLOCKING**" else "" end)' \
  | sort -t'#' -k2 -n

# ------------------------------------------- issues open against shipped work
note ""; note "## Check these — an open issue whose ticket number appears on main"
note ""
note "*A commit naming the ticket is not proof the ticket is done: partial work counts. Each row needs a look, not a close.*"
while read -r num title; do
  tkt="$(printf '%s' "$title" | grep -oE 'T[0-9]{3}' | head -1 || true)"
  [ -z "$tkt" ] && continue
  if g log --oneline origin/main --grep="$tkt" | grep -q .; then
    note "- **#$num open, but $tkt appears on main** — $title"
    fail=1
  fi
done < <(gh issue list --repo "$REPO" --state open --limit 200 --json number,title -q '.[] | "\(.number) \(.title)"')

# ---------------------------------------------------------------- merged work
# `gh` has no `--arg`. The previous form passed one, so gh rejected the call on
# every single run and the `||` fallback fired every time — printing the twenty
# newest merges with no date filter under a heading that said fourteen days.
# The date is spliced into the jq filter instead, and there is no fallback: if
# this breaks it should be visible rather than quietly answering a different
# question.
note ""; note "## Merged in the last 14 days"
SINCE="$(date -u -v-14d +%Y-%m-%d 2>/dev/null || date -u -d '14 days ago' +%Y-%m-%d)"
gh pr list --repo "$REPO" --state merged --limit 100 --json number,title,mergedAt \
  -q '.[] | select(.mergedAt[0:10] >= "'"$SINCE"'") | "- #\(.number) \(.mergedAt[0:10]) \(.title)"'

# ----------------------------------------------------------------- scenarios
note ""; note "## Scenarios by status"
for st in approved building draft deferred superseded; do
  hits="$(grep -l "^status: $st$" "$PLAN_REPO"/planning/scenario-F*.md 2>/dev/null || true)"
  [ -z "$hits" ] && continue
  note ""; note "**$st**"
  for f in $hits; do
    id="$(sed -n 's/^id: //p' "$f" | head -1)"
    ti="$(sed -n 's/^title: //p' "$f" | head -1)"
    note "- $ti [$id]"
  done
done

# -------------------------------------------------------------- to retire
note ""; note "## To retire — residue still on main"
for r in register-vendor "vendors/\[slug\]" "business/\[slug\]" you/vendor following; do
  p="$(g ls-tree -r origin/main --name-only | grep -E "src/app/$r.*/page\.tsx" | head -1 || true)"
  [ -n "$p" ] && note "- \`/${r//\\/}\` still present — $p"
done
g show origin/main:supabase/migrations/002_members.sql 2>/dev/null | grep -q maker_mode_enabled \
  && note "- \`members.maker_mode_enabled\` still in the schema"

# ------------------------------------------------------------------ ontology
# The link registry IS `src/ontology/links.ts` — reading that file is reading
# the source, not grepping for a proxy of it, so guard rail 4 is satisfied.
#
# What this deliberately does NOT do is re-derive the drift verdict.
# `scripts/ontology-drift.ts` in the code repo is that measurement, it runs
# daily, and its answer is reported under "What CI last said" below. Two
# answers to one question is the failure this repo is named for.
#
# What it reports is the SHAPE of the registry — how many relationships are
# declared and which are declared-but-unbuilt. That is invisible everywhere
# else: the drift job is silent when clean by design, so a link sitting at
# `built: false` for a month produces no signal at all.
note ""; note "## The ontology — what is declared"
note ""
if LINKS="$(g show origin/main:src/ontology/links.ts 2>/dev/null)"; then
  printf '%s' "$LINKS" | python3 -c '
import re, sys
src = sys.stdin.read()
rows = []
for m in re.finditer(r"name:\s*(['\''\"])((?:\\\\.|(?!\1).)*)\1", src):
    tail = src[m.end():]
    nxt = re.search(r"\bname:\s*['\''\"]", tail)
    scope = tail[:nxt.start()] if nxt else tail
    b = re.search(r"\bbuilt:\s*(true|false)", scope)
    if b:
        rows.append((m.group(2), b.group(1) == "true"))
built = [n for n, b in rows if b]
unbuilt = [n for n, b in rows if not b]
print(f"- **{len(rows)} link types declared**, {len(built)} built.")
if unbuilt:
    print(f"- **Declared but not built ({len(unbuilt)})** — the relationship is named and nothing writes it yet:")
    for n in unbuilt:
        print(f"  - {n}")
print("- Object types are deferred on purpose: a noun gets a declaration the next")
print("  time a handler touching it is edited. Not a gap to close in one pass.")
' || note "- **Could not parse the registry.** Its shape has changed; the parser in \`state.sh\` needs a look."
else
  note "- **\`src/ontology/links.ts\` is not on origin/main.** The registry has moved or gone."
fi

# ------------------------------------------------------------ what CI reports
# Both of these are silent-when-clean jobs. That is right for a gate and wrong
# for a status report: a green that nobody sees is indistinguishable from a job
# that stopped running. So their last conclusion is stated here, including when
# it is green, and including how long ago it ran.
note ""; note "## What CI last said in the code repo"
note ""
for wf in deploy-health.yml ci.yml; do
  row="$(gh run list --repo "$REPO" --workflow "$wf" --branch main --limit 1 \
        --json databaseId,conclusion,createdAt,status \
        -q '.[] | "\(.databaseId)\t\(.conclusion // .status)\t\(.createdAt[0:10])"' 2>/dev/null || true)"
  if [ -z "$row" ]; then
    note "- **\`$wf\`** — no run found. A workflow that has never run is not a passing one."
    continue
  fi
  id="$(printf '%s' "$row" | cut -f1)"
  concl="$(printf '%s' "$row" | cut -f2)"
  when="$(printf '%s' "$row" | cut -f3)"
  note "- **\`$wf\`** — $concl, $when"
  gh run view "$id" --repo "$REPO" --json jobs \
    -q '.jobs[] | "  - \(.name): \(.conclusion // .status)"' 2>/dev/null || true
  [ "$concl" = "failure" ] && fail=1
done

# ------------------------------------------------------------------- counts
note ""; note "## Measured, not estimated"
if INV="$(g show "origin/main:$INVENTORY_PATH" 2>/dev/null)"; then
  note "- Copy: $(printf '%s' "$INV" | grep -oE '[0-9]+ strings across [0-9]+ files' | head -1) — source \`$INVENTORY_PATH\` on origin/main"
else
  note "- **No copy inventory found. Do not substitute a grep** — regenerate the inventory instead."
fi
note "- Routes on origin/main: $(g ls-tree -r origin/main --name-only | grep -c 'src/app.*/page\.tsx')"
note "- Migrations on origin/main: $(g ls-tree -r origin/main --name-only | grep -c 'supabase/migrations/.*\.sql')"

note ""
[ "$fail" -eq 1 ] && note "> **Rows flagged above need a human look before the working lists are trusted.**"
exit 0
