#!/usr/bin/env bash
# Emits the facts WHERE-IT-IS.md's working lists are built from.
# Judgement sections are NOT produced here — see planning/LIVING-DOCS.md.
#
# Usage: bash scripts/state.sh [path-to-socialus-web]   (default ../socialus-web)
set -euo pipefail

PLAN_REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CODE_REPO="${1:-$(cd "$PLAN_REPO/../socialus-web" && pwd)}"
g() { git -C "$CODE_REPO" --no-optional-locks "$@"; }
fail=0
note() { printf '%s\n' "$*"; }

# ---------------------------------------------------------------- guard rails
# Four checks encoded from mistakes made building WHERE-IT-IS.md by hand.
# See socialus-web #96.

# 1. Never read an unfetched checkout.
for r in "$PLAN_REPO" "$CODE_REPO"; do
  git -C "$r" fetch --all --prune --quiet || { echo "FATAL: fetch failed in $r" >&2; exit 1; }
done

# 2. Never use --no-merged here: this repo squash-merges, so a merged branch's
#    tip is never an ancestor of main and is listed unmerged forever.
BANNED="no""-merged"
if grep -rhs -- "--$BANNED" "$PLAN_REPO/scripts" 2>/dev/null | grep -v '^[[:space:]]*#' | grep -qv 'BANNED='; then
  echo "FATAL: --$BANNED used in a script; meaningless in a squash-merging repo" >&2; exit 1
fi

# 3. gh must be authenticated, or issue state is guesswork.
gh auth status >/dev/null 2>&1 || { echo "FATAL: gh not authenticated" >&2; exit 1; }

# 4. Prefer an existing measurement to a grep.
INVENTORY_PATH="docs/copy-inventory.md"   # read from origin/main, never the working tree

REPO="$(g remote get-url origin)"; REPO="${REPO%.git}"; REPO="${REPO#*github.com/}"; REPO="${REPO#*github.com:}"
MAIN="$(g rev-parse --short origin/main)"
MAIN_DATE="$(g log -1 --format=%ad --date=short origin/main)"
LOCAL="$(g rev-parse --short HEAD 2>/dev/null || echo none)"

cat <<HDR
<!-- generated by scripts/state.sh on $(date -u +%Y-%m-%dT%H:%MZ) -->
<!-- origin/main $MAIN ($MAIN_DATE) · local HEAD $LOCAL · fetched -->
HDR
[ "$LOCAL" != "$MAIN" ] && note "" && note "> **Local checkout is not on origin/main** ($LOCAL vs $MAIN). Facts below come from origin/main."

# ------------------------------------------------------------------- to build
note ""; note "## To build — open issues"
gh issue list --repo "$REPO" --state open --limit 200 \
  --json number,title,labels \
  -q '.[] | "- #\(.number) \(.title)" + (if (.labels|map(.name)|index("launch-blocking")) then "  **LAUNCH-BLOCKING**" else "" end)' \
  | sort -t'#' -k2 -n

# ------------------------------------------- issues open against shipped work
note ""; note "## Check these — an open issue whose ticket number appears on main"
note ""
note "*A commit naming the ticket is not proof the ticket is done: partial work counts. Each row needs a look, not a close.*"
while read -r num title; do
  tkt="$(printf '%s' "$title" | grep -oE 'T[0-9]{3}' | head -1 || true)"
  [ -z "$tkt" ] && continue
  if g log --oneline origin/main --grep="$tkt" | grep -q .; then
    note "- **#$num open, but $tkt appears on main** — $title"
    fail=1
  fi
done < <(gh issue list --repo "$REPO" --state open --limit 200 --json number,title -q '.[] | "\(.number) \(.title)"')

# ---------------------------------------------------------------- merged work
note ""; note "## Merged in the last 14 days"
gh pr list --repo "$REPO" --state merged --limit 50 \
  --json number,title,mergedAt \
  -q --arg since "$(date -u -v-14d +%Y-%m-%d 2>/dev/null || date -u -d '14 days ago' +%Y-%m-%d)" \
  '.[] | select(.mergedAt[0:10] >= $since) | "- #\(.number) \(.mergedAt[0:10]) \(.title)"' 2>/dev/null \
  || gh pr list --repo "$REPO" --state merged --limit 20 --json number,title,mergedAt -q '.[] | "- #\(.number) \(.mergedAt[0:10]) \(.title)"'

# ----------------------------------------------------------------- scenarios
note ""; note "## Scenarios by status"
for st in approved building draft deferred superseded; do
  hits="$(grep -l "^status: $st$" "$PLAN_REPO"/planning/scenario-F*.md 2>/dev/null || true)"
  [ -z "$hits" ] && continue
  note ""; note "**$st**"
  for f in $hits; do
    id="$(sed -n 's/^id: //p' "$f" | head -1)"
    ti="$(sed -n 's/^title: //p' "$f" | head -1)"
    note "- $ti [$id]"
  done
done

# -------------------------------------------------------------- to retire
note ""; note "## To retire — residue still on main"
for r in register-vendor "vendors/\[slug\]" "business/\[slug\]" you/vendor following; do
  p="$(g ls-tree -r origin/main --name-only | grep -E "src/app/$r.*/page\.tsx" | head -1 || true)"
  [ -n "$p" ] && note "- \`/${r//\\/}\` still present — $p"
done
g show origin/main:supabase/migrations/002_members.sql 2>/dev/null | grep -q maker_mode_enabled \
  && note "- \`members.maker_mode_enabled\` still in the schema"

# ------------------------------------------------------------------- counts
note ""; note "## Measured, not estimated"
if INV="$(g show "origin/main:$INVENTORY_PATH" 2>/dev/null)"; then
  note "- Copy: $(printf '%s' "$INV" | grep -oE '[0-9]+ strings across [0-9]+ files' | head -1) — source \`$INVENTORY_PATH\` on origin/main"
else
  note "- **No copy inventory found. Do not substitute a grep** — regenerate the inventory instead."
fi
note "- Routes on origin/main: $(g ls-tree -r origin/main --name-only | grep -c 'src/app.*/page\.tsx')"
note "- Migrations on origin/main: $(g ls-tree -r origin/main --name-only | grep -c 'supabase/migrations/.*\.sql')"

note ""
[ "$fail" -eq 1 ] && note "> **Rows flagged above need a human look before the working lists are trusted.**"
exit 0
