#!/usr/bin/env bash
# Writes README.md from data. Never hand-edit README.md — re-run this instead.
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
REPO="donlafranchi/socialus-web"

days_left=$(( ( $(date -d 2026-10-30 +%s 2>/dev/null || date -j -f %Y-%m-%d 2026-10-30 +%s) - $(date +%s) ) / 86400 ))

scenario_title() {
  local f="$1"
  local file
  file=$(ls planning/scenario-"$f"-*.md 2>/dev/null | head -1)
  if [ -n "$file" ]; then
    grep -m1 -E '^# ' "$file" | sed -E "s/^#\s*//; s/^${f}:\s*//"
  else
    echo "$f"
  fi
}

# number \t title \t state \t deferred(y/n)
all=$(gh issue list -R "$REPO" --state all --json number,title,state,labels --limit 200 \
  --jq '.[] | [.number, .title, .state, (any(.labels[]; .name=="deferred") | tostring)] | @tsv')

open_f=$(echo "$all" | awk -F'\t' '$3=="OPEN"{print $2}' | grep -oE '^F[0-9]+' | sort -u)
closed_f=$(echo "$all" | awk -F'\t' '$3=="CLOSED"{print $2}' | grep -oE '^F[0-9]+' | sort -u)
deferred_f=$(echo "$all" | awk -F'\t' '$4=="true"{print $2}' | grep -oE '^F[0-9]+' | sort -u)

{
  echo "<!-- Generated by scripts/view.sh — never hand-edit. Re-run the script to refresh. -->"
  echo
  echo "# SocialUs — launch 2026-10-30, $days_left days left"
  echo
  echo "## Built"
  for f in $closed_f; do
    echo "$open_f" | grep -qx "$f" || echo "- $f: $(scenario_title "$f")"
  done
  echo
  echo "## Building"
  for f in $open_f; do
    echo "$deferred_f" | grep -qx "$f" && continue
    echo "- $f: $(scenario_title "$f")"
  done
  echo
  echo "## Next"
  sed -n '/^## Next/,/^## /p' ROADMAP.md | sed '1d;$d'
  echo
  echo "## Later"
  sed -n '/^## Later/,/^## /p' ROADMAP.md | sed '1d;$d'
  echo
  echo "## Deferred"
  for f in $deferred_f; do
    echo "- $f: $(scenario_title "$f")"
  done
} > README.md

echo "wrote README.md"
